package com.roomvibe.data

import com.roomvibe.data.entity.Reading
import com.roomvibe.data.entity.Sensor
import org.json.JSONArray
import org.json.JSONObject

/**
 * JSON (de)serialization for backup/restore. Format is a single object:
 *   { "version": 1, "exportedAtMs": <long>, "sensors": [...], "readings": [...] }
 *
 * Reading ids are intentionally omitted — on restore they are re-inserted with
 * autogenerated ids and de-duplicated by the (sensorAddress, timestampMs) index,
 * so a backup can be merged into a populated database safely.
 */
object BackupSerializer {
    const val VERSION = 1

    fun toJson(sensors: List<Sensor>, readings: List<Reading>): String {
        val root = JSONObject()
        root.put("version", VERSION)
        root.put("exportedAtMs", System.currentTimeMillis())

        val sArr = JSONArray()
        for (s in sensors) {
            sArr.put(JSONObject().apply {
                put("address", s.address)
                put("name", s.name)
                put("alias", s.alias ?: JSONObject.NULL)
                put("lastSyncMs", s.lastSyncMs)
                put("lastHistoryIndex", s.lastHistoryIndex)
            })
        }
        root.put("sensors", sArr)

        val rArr = JSONArray()
        for (r in readings) {
            rArr.put(JSONObject().apply {
                put("a", r.sensorAddress)
                put("t", r.timestampMs)
                put("tc", r.temperatureCelsius.toDouble())
                put("h", r.humidityPercent)
                put("tmn", r.tempMinC.toDouble())
                put("tmx", r.tempMaxC.toDouble())
                put("hmn", r.humMin)
                put("hmx", r.humMax)
                put("b", r.batteryPercent)
            })
        }
        root.put("readings", rArr)
        return root.toString()
    }

    data class Parsed(val sensors: List<Sensor>, val readings: List<Reading>)

    fun fromJson(json: String): Parsed {
        val root = JSONObject(json)

        val sensors = ArrayList<Sensor>()
        val sArr = root.optJSONArray("sensors") ?: JSONArray()
        for (i in 0 until sArr.length()) {
            val o = sArr.getJSONObject(i)
            sensors.add(
                Sensor(
                    address = o.getString("address"),
                    name = o.optString("name", "LYWSD03MMC"),
                    alias = if (o.isNull("alias")) null else o.optString("alias", null),
                    lastSyncMs = o.optLong("lastSyncMs", 0L),
                    lastHistoryIndex = o.optInt("lastHistoryIndex", -1)
                )
            )
        }

        val readings = ArrayList<Reading>()
        val rArr = root.optJSONArray("readings") ?: JSONArray()
        for (i in 0 until rArr.length()) {
            val o = rArr.getJSONObject(i)
            readings.add(
                Reading(
                    id = 0,
                    sensorAddress = o.getString("a"),
                    timestampMs = o.getLong("t"),
                    temperatureCelsius = o.getDouble("tc").toFloat(),
                    humidityPercent = o.getInt("h"),
                    tempMinC = o.getDouble("tmn").toFloat(),
                    tempMaxC = o.getDouble("tmx").toFloat(),
                    humMin = o.getInt("hmn"),
                    humMax = o.getInt("hmx"),
                    batteryPercent = o.optInt("b", 0)
                )
            )
        }
        return Parsed(sensors, readings)
    }
}
